### ISSUE TITLE
Published Pages donot reflect Angular material

### ISSUE THREAD

**Issue by SteffiKeranJ** [cmgriffing/scully-gh-pages-action#15]
This is my workflow yaml.
```
name: Scully Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: master
          build-args: npm run build
          scully-args: npm run scully
```
The workflow succeeds, but when I check the deployed site https://steffikeranj.github.io/Angular-Scully-Demo, I am not able to find the Material theme being rendered. Any workaround for this? (My repo is : https://github.com/SteffiKeranJ/Angular-Scully-Demo)
