### ISSUE TITLE
(help needed) Build failure caused by Scully dependencies issue

### ISSUE THREAD

**Issue by morenoisidro** [cmgriffing/scully-gh-pages-action#25]
### Problem
I've recently setup this GitHub action and faced a [known issue](https://github.com/scullyio/scully/issues/1606#issuecomment-1264384190) from Scully project that I managed to solve locally with a force install.

### Question
> Is there anything I could do from the workflow file in order to overcome this problem? any ideas?

Thanks!!

#### Build output:

![image](https://user-images.githubusercontent.com/30235159/193421025-35711068-0ad0-4072-b7b6-a51a1543a3a8.png)

### Setup
This is my workflow file: https://github.com/morenoisidro/ng-kitsune/blob/site/.github/workflows/site.yml
```

name: Scully Publish

on:
  push:
    branches:
      - site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
```
